const state = { roster: [], plan: null, reviewed: new Set() };
const monthNames = ['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
const dayNames = ['Dom','Lun','Mar','Mer','Gio','Ven','Sab'];
const demoRoster = [['Alessio Bianchi','A','Coordinatore'],['Marta Riva','A','Operatore'],['Luca Neri','A','Operatore'],['Sara Villa','A','Operatore'],['Davide Conti','B','Coordinatore'],['Elena Galli','B','Operatore'],['Marco Fabbri','B','Operatore'],['Irene Costa','B','Operatore'],['Paolo Sala','C','Coordinatore'],['Chiara De Luca','C','Operatore'],['Andrea Greco','C','Operatore'],['Nadia Fontana','C','Operatore'],['Giorgio Parisi','D','Coordinatore'],['Laura Moretti','D','Operatore'],['Stefano Rizzo','D','Operatore'],['Anna Ferri','D','Operatore'],['Tommaso Serra','A','Operatore'],['Beatrice Longo','B','Operatore']].map(([name,team,role]) => ({name,team,role,availability:'Completa'}));
const $ = selector => document.querySelector(selector);
function init() { const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), 1); const end = new Date(now.getFullYear(), now.getMonth() + 1, 0); $('#start-date').value = toInputDate(start); $('#end-date').value = toInputDate(end); $('#file-input').addEventListener('change', event => readFile(event.target.files[0])); $('#demo-button').addEventListener('click', () => loadRoster(demoRoster, 'Roster di esempio')); $('#generate-button').addEventListener('click', generatePlan); $('#download-button').addEventListener('click', downloadPlan); $('#reorder-button').addEventListener('click', reorderSelected); $('#reset-button').addEventListener('click', resetApp); $('#calendar-wrap').addEventListener('click', handleAssignmentClick); const zone = $('#upload-zone'); ['dragenter','dragover'].forEach(type => zone.addEventListener(type, event => { event.preventDefault(); zone.classList.add('dragging'); })); ['dragleave','drop'].forEach(type => zone.addEventListener(type, event => { event.preventDefault(); zone.classList.remove('dragging'); })); zone.addEventListener('drop', event => readFile(event.dataTransfer.files[0])); }
function readFile(file) { if (!file) return; const reader = new FileReader(); reader.onload = event => { try { const workbook = XLSX.read(event.target.result, {type:'array'}); const rows = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], {header:1, defval:''}); const header = rows.shift().map(value => String(value).toLowerCase()); const indexOf = (names, fallback) => Math.max(0, header.findIndex(value => names.some(name => value.includes(name))) || fallback); const name = indexOf(['nome','nominativo','persona'],0); const team = indexOf(['squadra','team','gruppo'],1); const role = indexOf(['qualifica','ruolo','mansione'],2); const roster = rows.filter(row => row[name]).map(row => ({name:String(row[name]).trim(),team:String(row[team] || 'A').trim(),role:String(row[role] || 'Operatore').trim(),availability:'Completa'})); if (!roster.length) throw new Error('nessun nominativo riconosciuto'); loadRoster(roster,file.name); } catch (error) { alert(`Impossibile leggere il file: ${error.message}`); } }; reader.readAsArrayBuffer(file); }
function loadRoster(roster,label) { state.roster = roster; state.plan = null; state.reviewed.clear(); $('#upload-title').textContent = label; $('#upload-subtitle').textContent = `${roster.length} persone riconosciute`; $('#roster-count').textContent = `${roster.length} persone`; $('#save-status').textContent = 'Dati caricati'; $('#roster-body').innerHTML = roster.map(person => `<tr><td><strong>${escapeHtml(person.name)}</strong></td><td><span class="team-badge">${escapeHtml(person.team)}</span></td><td>${escapeHtml(person.role)}</td><td class="availability">● ${escapeHtml(person.availability)}</td></tr>`).join(''); updateStats(); renderEmpty('Pronto per generare la turnazione'); }
function buildGroups() { const people = [...state.roster].sort((a,b) => a.team.localeCompare(b.team)); const groups = []; for (let index = 0; index < people.length; index += 3) groups.push(people.slice(index,index + 3)); return groups; }
function generatePlan() { if (state.roster.length < 6) return alert('Servono almeno 6 persone.'); const startDate = parseInputDate($('#start-date').value); const endDate = parseInputDate($('#end-date').value); if (!startDate || !endDate || startDate > endDate) return alert('Seleziona un intervallo di date valido.'); const groups = buildGroups(); const assignments = []; let internalCount = 0; let externalCount = 0; let index = 0; for (let date = new Date(startDate); date <= endDate; date.setDate(date.getDate() + 1)) { const current = new Date(date); const weekend = current.getDay() === 0 || current.getDay() === 6; if (weekend && !$('#weekend-toggle').checked) continue; const rotation = index % groups.length; const first = groups[rotation]; const second = groups[(rotation + 1 + ($('#random-toggle').checked && index % 3 === 0 ? 1 : 0)) % groups.length]; assignments.push({day:current.getDate(),date:current,weekend,internal:index % 2 ? second : first,external:index % 2 ? first : second}); internalCount++; externalCount++; index++; } state.reviewed.clear(); state.plan = {startDate,endDate,groups,assignments,internalCount,externalCount,startDay:Number($('#week-start').value)}; $('#plan-title').textContent = `${formatDate(startDate)} - ${formatDate(endDate)}`; $('#download-button').disabled = false; $('#save-status').textContent = 'Piano pronto'; updateStats(); renderCalendar(); }
function updateStats() { const values = $('#stats-row').querySelectorAll('.stat strong'); if (!state.plan) { values.forEach(value => value.textContent = '—'); return updateReviewControls(); } values[0].textContent = state.roster.length; values[1].textContent = state.plan.groups.length; values[2].textContent = new Set(state.plan.assignments.map(item => item.day)).size; values[3].textContent = `${state.plan.internalCount} / ${state.plan.externalCount}`; updateReviewControls(); }
function renderCalendar() { const plan = state.plan; const months = new Map(); plan.assignments.forEach(item => { const key = `${item.date.getFullYear()}-${item.date.getMonth()}`; if (!months.has(key)) months.set(key, []); months.get(key).push(item); }); const sections = [...months.values()].map(items => { const first = items[0].date; const offset = (new Date(first.getFullYear(), first.getMonth(), 1).getDay() - plan.startDay + 7) % 7; const cells = Array.from({length:offset}, () => '<div class="day-card empty"></div>'); items.forEach(item => cells.push(`<article class="day-card ${item.weekend ? 'weekend' : ''}"><div class="day-number"><span>${String(item.day).padStart(2,'0')}</span><small>${dayNames[item.date.getDay()]}</small></div>${assignment(item.internal,'Interno',item.weekend,item.date)}${assignment(item.external,'Esterno',item.weekend,item.date)}</article>`)); return `<section class="calendar-month"><h3 class="calendar-month-title">${monthNames[first.getMonth()]} ${first.getFullYear()}</h3><div class="calendar"><div class="day-head">Lun</div><div class="day-head">Mar</div><div class="day-head">Mer</div><div class="day-head">Gio</div><div class="day-head">Ven</div><div class="day-head">Sab</div><div class="day-head">Dom</div>${cells.join('')}</div></section>`; }); $('#calendar-wrap').innerHTML = sections.join(''); updateReviewControls(); }
function assignment(group,service,weekend,date) { const initials = group.map(person => person.name.split(' ').map(part => part[0]).join('')).join(' · '); const reviewKey = toInputDate(date); const selected = state.reviewed.has(reviewKey) ? ' selected' : ''; return `<div class="assignment ${service === 'Esterno' ? 'external' : ''} ${weekend ? 'weekend-service' : ''}${selected}" data-review-key="${reviewKey}" role="button" tabindex="0" aria-pressed="${selected ? 'true' : 'false'}"><strong>${service}</strong><span>${initials}</span></div>`; }
function handleAssignmentClick(event) { const target = event.target.closest('.assignment'); if (!target || !state.plan) return; const key = target.dataset.reviewKey; if (state.reviewed.has(key)) state.reviewed.delete(key); else state.reviewed.add(key); renderCalendar(); }
function updateReviewControls() { const count = state.reviewed.size; $('#review-count').textContent = `${count} giorni`; $('#reorder-button').disabled = !state.plan || count === 0; }
function reorderSelected() { if (!state.plan || !state.reviewed.size) return; state.reviewed.forEach(dateValue => { const item = state.plan.assignments.find(assignmentItem => toInputDate(assignmentItem.date) === dateValue); if (!item) return; const pairs = []; state.plan.groups.forEach(internal => state.plan.groups.forEach(external => { if (internal === external || internal === item.internal || external === item.external) return; pairs.push({internal,external,score:groupScore(internal,'internal',item) + groupScore(external,'external',item)}); })); if (!pairs.length) return; const best = pairs.sort((left,right) => left.score - right.score)[0]; item.internal = best.internal; item.external = best.external; }); state.reviewed.clear(); $('#save-status').textContent = 'Sestine riordinate'; renderCalendar(); }
function groupScore(group, property, item) { return state.plan.assignments.reduce((score, candidate) => { if (candidate[property] === group) { const distance = Math.abs(candidate.date - item.date) / 86400000; if (distance === 0) return score + 100; if (distance <= 2) return score + 10 - distance; if (distance <= 5) return score + 3; return score + 1; } return score; }, 0); }
function renderEmpty(title) { $('#calendar-wrap').innerHTML = `<div class="empty-state"><div class="empty-icon">✦</div><h3>${title}</h3><p>Imposta i parametri e genera il piano.</p></div>`; $('#plan-title').textContent = 'Nessuna turnazione generata'; $('#download-button').disabled = true; updateReviewControls(); }
function downloadPlan() { if (!state.plan) return; const rows = [['Data','Giorno','Servizio interno','Servizio esterno']]; state.plan.assignments.forEach(item => rows.push([item.date.toLocaleDateString('it-IT'),dayNames[item.date.getDay()],item.internal.map(person => person.name).join(', '),item.external.map(person => person.name).join(', ')])); const sheet = XLSX.utils.aoa_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book,sheet,'Turnazione'); XLSX.writeFile(book,`turnazione-${toInputDate(state.plan.startDate)}-${toInputDate(state.plan.endDate)}.xlsx`); }
function resetApp() { location.reload(); }
function toInputDate(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function parseInputDate(value) { return value ? new Date(`${value}T00:00:00`) : null; }
function formatDate(date) { return date.toLocaleDateString('it-IT', {day:'2-digit', month:'short', year:'numeric'}); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[character])); }
init();
